apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deploymentname }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentname }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
