apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentname }}
spec:
  selector:
    app: {{ .Values.deploymentname }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: NodePort