apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-gin-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: <URL of your Git repository>
    path: <path to your Kubernetes manifests>
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
