apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-gin-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/naveenkumarvr/go-hello-world-demo.git
    path: ./deployment.yml
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
